### ISSUE TITLE
Unknow file extension ".ts" error

### ISSUE THREAD

**Issue by snyzzz** [kozennnn/BufferJS#1]
I can't use this package, it show me this error:

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Users\Snyz\Documents\gear-launcher\node_modules\buffer.ws\src\BufferWS.ts
←[90m    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)←[39m
←[90m    at Loader.getFormat (internal/modules/esm/loader.js:102:42)←[39m
←[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:231:31)←[39m
←[90m    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:58:21)←[39m
    at async Promise.all (index 0)
←[90m    at async link (internal/modules/esm/module_job.js:63:9)←[39m {
  code: ←[32m'ERR_UNKNOWN_FILE_EXTENSION'←[39m

It ask me to use Typescript but i don't want to use it just for this package :/

**Comment by mathishouis** [comment]
Hello, I am currently fixing this problem, I will commit the fix within a few minutes! Thanks for reporting this issue :smile_cat:

**Comment by mathishouis** [comment]
Fixed
